# Arbeitspaket (AP) 1: Management & Nutzung Relationale Daten

### Persönliche Angaben (bitte ergänzen)

<table>
  <tr>
    <td>Vorname:</td>
    <td>Alexander</td>
  </tr>
  <tr>
    <td>Nachname:</td>
    <td>Wielengowski</td>
  </tr>
  <tr>
    <td>Immatrikulationsnummer:</td>
    <td>24-672-380</td>
  </tr>
  <tr>
    <td>Modul:</td>
    <td>Data Science</td>
  </tr>
  <tr>
    <td>Prüfungsdatum / Raum / Zeit:</td>
    <td>07.10.2024 / Raum: SF O3.54 / 8:00 – 11:45</td>
  </tr>
  <tr>
    <td>Erlaubte Hilfsmittel:</td>
    <td>w.MA.XX.DS.24HS (Data Science)<br>Open Book, Eigener Computer, Internet-Zugang</td>
  </tr>
  <tr>
  <td>Nicht erlaubt:</td>
  <td>Nicht erlaubt ist der Einsatz beliebiger Formen von generativer KI (z.B. Copilot, ChatGPT) <br> sowie beliebige Formen von Kommunikation oder Kollaboration mit anderen Menschen.</td>
</tr>
</table>

## Bewertungskriterien

### <b style="color: gray;">(max. erreichbare Punkte: 48)</b>

<table>
  <thead>
    <tr>
      <th>Kategorie</th>
      <th>Beschreibung</th>
      <th>Punkteverteilung</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Code nicht lauffähig oder Ergebnisse nicht sinnvoll</td>
      <td>Der Code enthält Fehler, die verhindern, dass er ausgeführt werden kann (z.B. Syntaxfehler) oder es werden Ergebnisse ausgegeben, welche nicht zur Fragestellung passen.</td>
      <td>0 Punkte</td>
    </tr>
    <tr>
      <td>Code lauffähig, aber mit gravierenden Mängeln</td>
      <td>Der Code läuft, aber die Ergebnisse sind aufgrund wesentlicher Fehler unvollständig (z.B. fehlende Joins, gravierende Fehler in SQL-Abfragen). Nur geringer Fortschritt erkennbar.</td>
      <td>25% der max. erreichbaren Punkte</td>
    </tr>
    <tr>
      <td>Code lauffähig, aber mit mittleren Mängeln</td>
      <td>Der Code läuft und liefert teilweise korrekte Ergebnisse, aber es gibt grössere Fehler (z.B. fehlende Spalten, unvollständige SQL-Abfragen). Die Ergebnisse sind nachvollziehbar, aber unvollständig oder ungenau.</td>
      <td>50% der max. erreichbaren Punkte</td>
    </tr>
    <tr>
      <td>Code lauffähig, aber mit minimalen Mängeln</td>
      <td>Der Code läuft und liefert ein weitgehend korrektes Ergebnis, aber kleinere Fehler (z.B. falsche oder fehlende Sortierung, Rundung von Werten falsch) beeinträchtigen die Vollständigkeit des Ergebnisses.</td>
      <td>75% der max. erreichbaren Punkte</td>
    </tr>
    <tr>
      <td>Code lauffähig und korrekt</td>
      <td>Der Code läuft einwandfrei und liefert das korrekte Ergebnis ohne Mängel.</td>
      <td>100% der max. erreichbaren Punkte</td>
    </tr>
  </tbody>
</table>

## Python Libraries und Settings

In [22]:
# Libraries
import os
import sqlite3
import pandas as pd
from sqlalchemy import create_engine, text

# Settings
import warnings
warnings.filterwarnings("ignore")

# Working directory
print(os.getcwd())

/

## <b>Vorbereitung (Dieser Teil wird <u>nicht</u> bewertet!)</b>

#### <b>1.) Starten Sie eine GitHub Codespaces Instanz auf Basis Ihres Forks des folgenden GitHub Repositories:</b>

##### GitHub-Repository: https://github.com/mario-gellrich-zhaw/python_postgresql_pgadmin

#### <b>2.) Erstellen und Testen Sie eine Datenbankverbindung mit der 'postgres' Datenbank.</b>

In [23]:
# Set up für Datenbankverbindung
user = "pgadmin"
password = "geheim"
host = "localhost"
port = "5432"
database = "postgres"

# Erstellen der Connection URL
db_connection_url = "postgresql://" + user + ":" + password +\
                    "@" + host + ":" + port + "/" + database

# Erstellen SQLAlchemy Engine
engine = create_engine(db_connection_url)

# Test der Datenbankverbindung
with engine.connect() as connection:
    result = connection.execute(text('SELECT current_database()'))
    print(result.fetchone())

# Verbindung trennen
engine.dispose()

('postgres',)

#### <b>3.) Lesen Sie die Tabellenblätter aus 'car_dealership_data.xlsx' ein, und speichern Sie diese in separaten DataFrames.</b>

In [24]:
# Pfad zur .xlsx Datei
path = 'workspace/car_dealer_data.xlsx'

# Einlesen der Daten aus Excel File
df_cars = pd.read_excel(path, sheet_name='Cars')
df_customers = pd.read_excel(path, sheet_name='Customers')
df_sales = pd.read_excel(path, sheet_name='Sales')
df_salespersons = pd.read_excel(path, sheet_name='SalesPersons')
df_mechanics = pd.read_excel(path, sheet_name='Mechanics')
df_servicerecords = pd.read_excel(path, sheet_name='ServiceRecords')

# Anpassen der Spaltennamen zu 'lowercase'
df_cars.columns = df_cars.columns.str.lower()
df_customers.columns = df_customers.columns.str.lower()
df_sales.columns = df_sales.columns.str.lower()
df_salespersons.columns = df_salespersons.columns.str.lower()
df_mechanics.columns = df_mechanics.columns.str.lower()
df_servicerecords.columns = df_servicerecords.columns.str.lower()

#### <b>4.) Schreiben Sie die erstellten DataFrames in separate Tabellen in Ihrer Datenbank.</b>

In [25]:
# Engine für Datenbankverbindung erstellen
engine = create_engine(db_connection_url)

# Schreiben der DataFrames in die Datenbank
df_cars.to_sql('cars', engine, if_exists='replace')
df_customers.to_sql('customers', engine, if_exists='replace')
df_sales.to_sql('sales', engine, if_exists='replace')
df_salespersons.to_sql('salespersons', engine, if_exists='replace')
df_mechanics.to_sql('mechanics', engine, if_exists='replace')
df_servicerecords.to_sql('servicerecords', engine, if_exists='replace')

# Datenbankverbindung trennen
engine.dispose()

<div style="background-color: #F0EAD6;">

#### <b> Hinweis! 

#### Falls etwas mit der PostgreSQL - Verbindung nicht funktioniert, verwenden Sie für die folgenden Aufgaben die SQLite Datenbank 'car_dealership.db'.</b>

#### <b> Das folgende Python-Codebeispiel demonstriert den Verbindungsaufbau mit der SQLite Datenbank mit Python.</b>

```python
# Engine für Datenbankverbindung erstellen
engine = create_engine('sqlite:///workspace/car_dealer_data.db')

# SQL Abfrage
df_sub = pd.read_sql_query("""SELECT *
                              FROM cars;""",
                          con=engine)

# Schliessen der Datenbankverbindung
engine.dispose()

df_sub 
```
</div>

## <b>Aufgaben (Dieser Teil wird bewertet!)</b>
<b style="color:blue;">Hinweise zu den folgenden Aufgabenstellungen:</b>
<ul style="color:blue;">
  <li>Erstellen Sie je Aufgabe eine SQL Abfrage und integrieren Sie diese in Ihren Python Code.</li>
  <li>Speichern Sie je Aufgabe die Ergebnistabelle in einem DataFrame und stellen Sie diesen ganz oder in Teilen (z.B. erste 5 Zeilen) dar.</li>
</ul>

#### <b>Aufgabe (1): Ermitteln Sie die Anzahl der durchgeführten Services mit ServiceDescription = 'Clutch Repair'.</b>
<b>Details zur Aufgabenstellung:</b>
- Sie finden die benötigten Informationen in der Tabelle 'ServiceRecords'.
- In der Ergebnistabelle muss die Anzahl der Services mit ServiceDescription = 'Clutch Repair' als ein Wert erscheinen.

<b style="color: gray;">(max. erreichbare Punkte: 4)</b>

In [26]:
# Engine für Datenbankverbindung erstellen
engine = create_engine(db_connection_url)

# Abfrage erstellen und in DataFrame speichern
df1 = pd.read_sql_query(''' SELECT count(servicedescription) as Numer_of_ServiceRepairs
                            FROM servicerecords
                            WHERE servicedescription='Clutch Repair'
                        ''', engine)


# Datenbankverbindung trennen
engine.dispose()

# Ergebnis anzeigen (Dataframe -Auschnitt genügt- mit Ergebnis der Abfrage)
df1

   numer_of_servicerepairs
0                      314

#### <b>Aufgabe (2): Ermitteln Sie den mittleren Preis aller Fahrzeuge nach Baujahr.</b>
<b>Details zur Aufgabenstellung:</b>
- Sie finden die benötigten Informationen in der Tabelle 'Cars'.
- Die Ergebnistabelle muss zwei Spalten beinhalten (Year, AveragePrice).

<b style="color: gray;">(max. erreichbare Punkte: 4)</b>

In [27]:
# Engine für Datenbankverbindung erstellen
engine = create_engine(db_connection_url)

# Abfrage erstellen und in DataFrame speichern
df2 = pd.read_sql_query(''' SELECT year, avg(price) as AveragePrice
                        FROM cars 
                        GROUP BY year
                        ''', engine)

### sidenote: casting & rounding not required as per task

# Datenbankverbindung trennen
engine.dispose()

# Ergebnis anzeigen (Dataframe -Auschnitt genügt- mit Ergebnis der Abfrage)
df2

   year  averageprice
0  2022  32748.917821
1  2020  32198.801506
2  2023  32782.659507
3  2019  32448.813473
4  2021  33337.026461

#### <b>Aufgabe (3): Listen Sie die Anzahl Fahrzeuge für jede Kombination aus Marke und Modell auf.</b>
<b>Details zur Aufgabenstellung:</b>
- Sie finden die benötigten Informationen in der Tabelle 'Cars'.
- Jede Marke und jedes Modell darf zusammen mit der entsprechenden Anzahl der Fahrzeuge nur einmal gezeigt werden.
- Die Ergebnistabelle muss drei Spalten beinhalten (Make, Model, NumberOfCars).
- Sortieren Sie die Ergebnistabelle absteigend nach der Anzahl der Fahrzeuge.

<b style="color: gray;">(max. erreichbare Punkte: 4)</b>

In [28]:
# Engine für Datenbankverbindung erstellen
engine = create_engine(db_connection_url)

# Abfrage erstellen und in DataFrame speichern
df3 = pd.read_sql_query('''SELECT make, model, count(carid) AS NumberOfCars
                        FROM cars 
                        GROUP BY make, model 
                        ORDER BY NumberOfCars DESC
                        ''', engine)

# Datenbankverbindung trennen
engine.dispose()

# Ergebnis anzeigen (Dataframe -Auschnitt genügt- mit Ergebnis der Abfrage)
df3

         make    model  numberofcars
0        Ford   Fiesta           179
1   Chevrolet   Malibu           179
2      Toyota    Camry           179
3         BMW     320i           178
4    Mercedes  E-Class           175
5        Ford  Mustang           164
6       Honda   Accord           163
7    Mercedes  C-Class           161
8      Toyota  Corolla           159
9   Chevrolet   Impala           158
10      Honda    Civic           155
11        BMW       X5           150

#### <b>Aufgabe (4): Ermitteln Sie die Anzahl der Fahrzeuge mit dem Status 'Available', gruppiert nach Marke.</b>
<b>Details zur Aufgabenstellung:</b>
- Sie finden die benötigten Informationen in der Tabelle 'Cars'.
- Die Ergebnistabelle muss nach der Anzahl Fahrzeuge absteigend sortiert sein.

<b style="color: gray;">(max. erreichbare Punkte: 4)</b>

In [29]:
# Engine für Datenbankverbindung erstellen
engine = create_engine(db_connection_url)

# Abfrage erstellen und in DataFrame speichern
df4 = pd.read_sql_query('''SELECT make,  count(carid) AS NumberOfCars
                        FROM cars 
                        GROUP BY make, status
                        HAVING status LIKE 'Available'
                        ORDER BY NumberOfCars DESC
                        ''', engine)

# Datenbankverbindung trennen
engine.dispose()

# Ergebnis anzeigen (Dataframe -Auschnitt genügt- mit Ergebnis der Abfrage)
df4

        make  numberofcars
0   Mercedes           125
1     Toyota           118
2        BMW           115
3  Chevrolet           110
4       Ford           105
5      Honda            99

#### <b>Aufgabe (5): Ermitteln Sie, wie viele Fahrzeuge jeder Verkäufer verkauft hat und zu welchem Gesamtpreis.</b>
<b>Details zur Aufgabenstellung:</b>
- Sie finden die benötigten Informationen in den Tabellen 'Salespersons' und 'Sales'.
- Die Ergebnistabelle muss die Anzahl der verkauften Fahrzeuge, den Gesamtpreis der Verkäufe sowie den Namen, Vornamen, Tel.nr. und Email der Verkäufer enthalten.
- Die Ergebnistabelle muss nach dem gerundeten Gesamtpreis absteigend sortiert sein.

<b style="color: gray;">(max. erreichbare Punkte: 8)</b>

In [30]:
# Engine für Datenbankverbindung erstellen
engine = create_engine(db_connection_url)

# Abfrage erstellen und in DataFrame speichern
df5 = pd.read_sql_query('''SELECT round(cast(sum(a.saleprice) as NUMERIC),2) as totalsales, count(a.saleid), b.lastname, b.firstname, b.phone, b.email
                        FROM sales AS a
                        JOIN salespersons AS b ON a.salespersonid = b.salespersonid
                        GROUP BY b.firstname, b.lastname, b.phone, b.email
                        ORDER BY totalsales DESC
                        ''', engine)

# Datenbankverbindung trennen
engine.dispose()

# Ergebnis anzeigen (Dataframe -Auschnitt genügt- mit Ergebnis der Abfrage)
df5

,totalsales,count,lastname,firstname,phone,email
0,8741578.45,261,Brown,Heather,+41 (0)46 288 75 19,heather.brown@example.com
1,8413807.47,260,Robinson,Lauren,+41 (0)71 214 12 13,lauren.robinson@example.com
2,8392149.63,259,Harris,Christine,+41 (0)61 523 86 58,christine.harris@example.com
3,8333139.56,263,Randall,Karen,+41 (0)66 616 17 40,karen.randall@example.com
4,8309576.34,254,Klein,Brian,+41 (0)77 449 26 62,brian.klein@example.com
5,8305445.39,248,Lyons,Robert,+41 (0)40 422 23 33,robert.lyons@example.com
6,7775226.86,251,Becker,Cathy,+41 (0)23 263 98 44,cathy.becker@example.com
7,7678064.65,244,Zhang,Michael,+41 (0)63 311 51 92,michael.zhang@example.com
8,7460279.34,236,Baxter,Ryan,+41 (0)40 706 53 70,ryan.baxter@example.com
9,7305422.86,224,Carter,Nicole,+41 (0)77 266 76 74,nicole.carter@example.com

##### <b>Aufgabe (6): Ermitteln Sie, welche Fahrzeuge im Januar 2024 verkauft wurden und zu welchem Verkaufspreis.</b>
<b>Details zur Aufgabenstellung:</b>
- Sie finden die benötigten Informationen in den Tabellen 'Sales', 'Cars', 'Customers' und 'Salespersons'.
- Die Ergebnistabelle muss die CarID, Marke, Modell, Verkaufspreis, Verkaufsdatum sowie die Vornamen und Namen der Kunden und Verkäufer beinhalten.
- Limitieren Sie die Anzahl der mit der SQL Abfrage zurückgegebenen Fahrzeuge auf 10.

<b>Tip:</b> 
- Das Verkausdatum (SaleDate in der Tabelle Sale) ist pro Tag angegeben. Für eine Abfrage nach Monat kann die SQL clause 'BETWEEN' verwendet werden.

<b style="color: gray;">(max. erreichbare Punkte: 8)</b>

In [31]:
# Engine für Datenbankverbindung erstellen
engine = create_engine(db_connection_url)

# Abfrage erstellen und in DataFrame speichern
df6 = pd.read_sql_query('''SELECT  b.carid, b.make, b.model, a.saleprice, a.saledate, c.firstname AS customer_firstname,
                                c.lastname AS customer_lastname, d.firstname AS salesperson_firstname, d.lastname AS salesperson_lastname
                        FROM sales AS a
                        JOIN cars AS b ON a.carid = b.carid
                        JOIN customers AS c ON a.customerid = c.customerid
                        JOIN salespersons AS d ON a.salespersonid = d.salespersonid
                        WHERE a.saledate BETWEEN '2024-01-01' AND '2024-01-31'
                        LIMIT 10
                        ''', engine)

# Datenbankverbindung trennen
engine.dispose()

# Ergebnis anzeigen (Dataframe -Auschnitt genügt- mit Ergebnis der Abfrage)
df6

,carid,make,model,saleprice,saledate,customer_firstname,customer_lastname,salesperson_firstname,salesperson_lastname
0,CEUEAOO14M,Chevrolet,Impala,27379.76,2024-01-04,Cameron,Green,Michael,Zhang
1,CLLG9QB51M,Mercedes,E-Class,19563.88,2024-01-23,Kenneth,Barrett,Michael,Zhang
2,CM5UWD1Q9X,Mercedes,E-Class,34580.80,2024-01-15,James,Mathis,Michael,Zhang
3,CF3DIPUJ5R,Ford,Mustang,17086.98,2024-01-02,Brian,Cox,Michael,Zhang
4,CFCPDZQ8WH,Mercedes,E-Class,43558.91,2024-01-24,Mary,Stewart,Heather,Brown
5,C304QNZWN2,BMW,X5,42655.98,2024-01-15,Derek,Weaver,Heather,Brown
6,C4X7NQ5T1S,Mercedes,E-Class,48374.91,2024-01-22,Sean,Floyd,Heather,Brown
7,CNXUP5BQHK,Toyota,Camry,33719.67,2024-01-28,Jacob,Cummings,Heather,Brown
8,C0SEQTTH41,Ford,Mustang,36241.33,2024-01-12,Kimberly,Farmer,Ryan,Baxter
9,C3953877E7,Toyota,Camry,42201.34,2024-01-14,Annette,Drake,Ryan,Baxter

#### <b>Aufgabe (7): Ermitteln Sie die durchschnittlichen Servicekosten pro Mechaniker.</b>
<b>Details zur Aufgabenstellung:</b>
- Sie finden die benötigten Informationen in den Tabellen 'Mechanics' und 'ServiceRecords'.
- Die Ergebnistabelle muss die Kontaktdaten (Vorname, Nachname, Telefonnummer, E-Mail) der Mechaniker enthalten
- Die Ergebnistabelle muss nach den durchschnittlichen Servicekosten absteigend sortiert sein.
- Die durchschnittlichen Servicekosten müssen auf zwei Nachkommastellen gerundet werden (z.B. 576.84).
- Die Ergebnistabelle muss nach den durchschnittlichen Servicekosten absteigend sortiert sein.


<b style="color: gray;">(max. erreichbare Punkte: 8)</b>

In [32]:
# Engine für Datenbankverbindung erstellen
engine = create_engine(db_connection_url)

# Abfrage erstellen und in DataFrame speichern
df7 = pd.read_sql_query('''
                        SELECT ROUND(CAST(avg(a.cost) AS Numeric),2) AS average_service_cost, 
                            b.firstname, b.lastname, b.phone, b.email 
                        FROM servicerecords AS a
                        JOIN mechanics AS b ON a.mechanicid = b.mechanicid
                        GROUP BY b.firstname, b.lastname, b.phone, b.email
                        ORDER BY average_service_cost DESC
                        ''', engine)

# Datenbankverbindung trennen
engine.dispose()

# Ergebnis anzeigen (Dataframe -Auschnitt genügt- mit Ergebnis der Abfrage)
df7

,average_service_cost,firstname,lastname,phone,email
0,383.88,Shannon,Larsen,+41 (0)41 390 74 67,shannon.larsen@example.com
1,374.70,Melissa,Miller,+41 (0)77 431 12 29,melissa.miller@example.com
2,366.16,Cynthia,Pittman,+41 (0)39 208 58 20,cynthia.pittman@example.com
3,363.38,Bryan,White,+41 (0)23 791 68 46,bryan.white@example.com
4,361.28,Tiffany,Wilson,+41 (0)22 475 52 27,tiffany.wilson@example.com
5,360.99,Bradley,Mckinney,+41 (0)23 859 32 52,bradley.mckinney@example.com
6,359.72,Lisa,Hall,+41 (0)56 904 84 24,lisa.hall@example.com
7,356.38,Erin,Williamson,+41 (0)65 305 62 20,erin.williamson@example.com
8,351.50,Courtney,Ford,+41 (0)50 651 77 58,courtney.ford@example.com
9,344.29,Cassandra,Sanford,+41 (0)26 322 84 52,cassandra.sanford@example.com

#### <b>Aufgabe (8): Ermitteln Sie, welche <u>nicht</u> verkauften Fahrzeuge, wie oft im Service waren und welche Servicekosten dabei entstanden sind.</b>
<b>Details zur Aufgabenstellung:</b>
- Sie finden die benötigten Informationen in den Tabellen 'Cars', 'Sales' und 'ServiceRecords'.
- Erstellen Sie eine Ergebnistabelle, welche die CarID, Marke, Modell, Baujahr sowie die Anzahl der Services und Summe der Servicekosten für jedes Fahrzeug enthält.
- Die Ergebnistabelle muss nach den Servicekosten absteigend sortiert sein.
- Limitieren Sie die Anzahl der mit der SQL Abfrage zurückgegebenen Fahrzeuge auf 10.

<b style="color: gray;">(max. erreichbare Punkte: 8)</b>

In [33]:
# Engine für Datenbankverbindung erstellen
engine = create_engine(db_connection_url)

# Abfrage erstellen und in DataFrame speichern
df8 = pd.read_sql_query('''
                        SELECT a.carid, a.make, a.model, count(b.serviceid) AS NumberOfServices, sum(b.cost) AS Total_Cost
                        FROM cars AS a
                        JOIN servicerecords AS b ON a.carid = b.carid
                        LEFT JOIN sales AS c ON a.carid = c.carid
                        GROUP BY a.carid, a.make, a.model, c.saleid
                        HAVING c.saleid IS NULL
                        ORDER BY Total_Cost DESC
                        LIMIT 10
                        ''', engine)

# Datenbankverbindung trennen
engine.dispose()

# Ergebnis anzeigen (Dataframe -Auschnitt genügt- mit Ergebnis der Abfrage)
df8

        carid      make    model  numberofservices  total_cost
0  CLD6FXBNYN  Mercedes  E-Class                 5      5512.0
1  CLXEYGE640  Mercedes  C-Class                 7      5427.0
2  C49WJO0KP1    Toyota    Camry                11      5281.0
3  C70S0HJ5RU    Toyota  Corolla                 5      5248.0
4  CEBAI7BS31       BMW     320i                 9      5086.0
5  CFYTQ16YSE    Toyota    Camry                 6      5078.0
6  CGDS2434FR    Toyota    Camry                 5      5010.0
7  CPXG4E13T0       BMW       X5                 5      4733.0
8  CKT2PK5NZ5    Toyota    Camry                 6      4718.0
9  CD3Z6191CK      Ford  Mustang                 8      4616.0

### Jupyter notebook --footer info-- (please always provide this at the end of each notebook)

In [21]:
import os
import platform
import socket
from platform import python_version
from datetime import datetime

print('-----------------------------------')
print(os.name.upper())
print(platform.system(), '|', platform.release())
print('Datetime:', datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
print('Python Version:', python_version())
print('IP Address:', socket.gethostbyname(socket.gethostname()))
print('-----------------------------------')

-----------------------------------
POSIX
Linux | 6.5.0-1025-azure
Datetime: 2024-10-07 07:24:14
Python Version: 3.11.10
IP Address: 172.18.0.2
-----------------------------------