# Test Exam: Management & Nutzung Relationale Daten

### Persönliche Angaben (bitte ergänzen)

<table>
  <tr>
    <td>Vorname:</td>
    <td>Alexander</td>
  </tr>
  <tr>
    <td>Nachname:</td>
    <td>Wielengowski</td>
  </tr>
  <tr>
    <td>Immatrikulationsnummer: </td>
    <td> 24-672-370 </td>
  </tr>
  <tr>
    <td>Modul:</td>
    <td>Data Science</td>
  </tr>
  <tr>
    <td>Prüfungsdatum / Raum / Zeit:</td>
    <td>07.10.2024 / Raum: SF O3.54 / 8:00 – 11:45</td>
  </tr>
  <tr>
    <td>Hilfsmittel:</td>
    <td>w.MA.XX.DS.24HS (Data Science)<br>Open Book, Eigener Computer, Internet-Zugang</td>
  </tr>
</table>

## Bewertungskriterien

### <b style="color: gray;">(max. erreichbare Punkte: 44)</b>

<table>
  <thead>
    <tr>
      <th>Kategorie</th>
      <th>Beschreibung</th>
      <th>Punkteverteilung</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Code nicht lauffähig oder Ergebnisse nicht sinnvoll</td>
      <td>Der Code enthält Fehler, die verhindern, dass er ausgeführt werden kann (z.B. Syntaxfehler) oder es werden Ergebnisse ausgegeben, welche nicht zur Fragestellung passen.</td>
      <td>0 Punkte</td>
    </tr>
    <tr>
      <td>Code lauffähig, aber mit gravierenden Mängeln</td>
      <td>Der Code läuft, aber die Ergebnisse sind aufgrund wesentlicher Fehler unvollständig (z.B. fehlende Joins, gravierende Fehler in SQL-Abfragen). Nur geringer Fortschritt erkennbar.</td>
      <td>25% der max. erreichbaren Punkte</td>
    </tr>
    <tr>
      <td>Code lauffähig, aber mit mittleren Mängeln</td>
      <td>Der Code läuft und liefert teilweise korrekte Ergebnisse, aber es gibt grössere Fehler (z.B. fehlende Spalten, unvollständige SQL-Abfragen). Die Ergebnisse sind nachvollziehbar, aber unvollständig oder ungenau.</td>
      <td>50% der max. erreichbaren Punkte</td>
    </tr>
    <tr>
      <td>Code lauffähig, aber mit minimalen Mängeln</td>
      <td>Der Code läuft und liefert ein weitgehend korrektes Ergebnis, aber kleinere Fehler (z.B. falsche oder fehlende Sortierung, Rundung von Werten falsch) beeinträchtigen die Vollständigkeit des Ergebnisses.</td>
      <td>75% der max. erreichbaren Punkte</td>
    </tr>
    <tr>
      <td>Code lauffähig und korrekt</td>
      <td>Der Code läuft einwandfrei und liefert das korrekte Ergebnis ohne Mängel.</td>
      <td>100% der max. erreichbaren Punkte</td>
    </tr>
  </tbody>
</table>

## Python Libraries und Settings

In [1]:
# Libraries
import os
import sqlite3
import pandas as pd
from sqlalchemy import create_engine, text

# Settings
import warnings
warnings.filterwarnings("ignore")

# Working directory
print(os.getcwd())

/workspace/AP1

## <b>Vorbereitung (Hinweis: dieser Teil wird nicht bewertet)</b>

#### <b>1.) Starten Sie eine GitHub Codespaces Instanz auf Basis Ihres Forks des folgenden GitHub Repositories:</b>

##### GitHub-Repository: https://github.com/mario-gellrich-zhaw/python_postgresql_pgadmin

#### <b>2.) Erstellen und Testen Sie die Datenbankverbindung mit der 'postgres' Datenbank.</b>

In [2]:
# Set up für Datenbankverbindung
user = "pgadmin"
password = "geheim"
host = "localhost"
port = "5432"
database = "postgres"

# Erstellen der Connection URL
db_connection_url = "postgresql://" + user + ":" + password +\
                    "@" + host + ":" + port + "/" + database

# Erstellen SQLAlchemy Engine
engine = create_engine(db_connection_url)

# Test der Datenbankverbindung
with engine.connect() as connection:
    result = connection.execute(text('SELECT current_database()'))
    print(result.fetchone())

# Verbindung trennen
engine.dispose()

('postgres',)

#### <b>3.) Lesen Sie die Tabellenblätter aus 'smartphone_dealer_data.xlsx' ein, und speichern Sie diese in separaten DataFrames.</b>

In [3]:
# Pfad zur .xlsx Datei
path = '/workspace/AP1/smartphone_dealer_data.xlsx'

# Einlesen der Daten aus Excel File
### bei Lesen von einer Excel Datei muss immer noch das Worksheet angegeben werden. Beim Lesen eienr CSV entfällt das natürlich
### DataFrame existieren nur im Memory!
df_phones = pd.read_excel(path, sheet_name='Phones')
df_customers = pd.read_excel(path, sheet_name='Customers')
df_sales = pd.read_excel(path, sheet_name='Sales')
df_salespersons = pd.read_excel(path, sheet_name='SalesPersons')
df_technicians = pd.read_excel(path, sheet_name='Technicians')
df_servicerecords = pd.read_excel(path, sheet_name='ServiceRecords')

# Anpassen der Spaltennamen zu 'lowercase'
df_phones.columns = df_phones.columns.str.lower()
df_customers.columns = df_customers.columns.str.lower()
df_sales.columns = df_sales.columns.str.lower()
df_salespersons.columns = df_salespersons.columns.str.lower()
df_technicians.columns = df_technicians.columns.str.lower()
df_servicerecords.columns = df_servicerecords.columns.str.lower()

#### <b>4.) Schreiben Sie die erstellten DataFrames in separate Tabellen in Ihrer Datenbank.</b>

In [4]:
# Engine für Datenbankverbindung erstellen
engine = create_engine(db_connection_url)

# Schreiben der DataFrames in die Datenbank
df_phones.to_sql('phones', engine, if_exists='replace', index=False)
df_customers.to_sql('customers', engine, if_exists='replace', index=False)
df_sales.to_sql('sales', engine, if_exists='replace', index=False)
df_salespersons.to_sql('salespersons', engine, if_exists='replace', index=False)
df_technicians.to_sql('technicians', engine, if_exists='replace', index=False)
df_servicerecords.to_sql('servicerecords', engine, if_exists='replace', index=False)

# Datenbankverbindung trennen
engine.dispose()

<div style="background-color: #F0EAD6;">

#### <b> Hinweis! 

#### Falls etwas mit Ihrer PostgreSQL Verbindung nicht funktionieren sollte, verwenden Sie für die folgenden Aufgaben die SQLite Datenbank 'smartphone_dealer_data.db'. Sie finden diese auf Moodle in der Woche 4 im Order 'AP01'. Schieben (per drag and drop) Sie dazu die SQLite-Datenbank von Ihrem lokalen PC in Ihre GitHub Codespaces Environment.</b>

#### <b> Das folgende Python-Codebeispiel demonstriert den Verbindungsaufbau mit der SQLite Datenbank mit Hilfe von Python.</b>

```python
# Engine für Datenbankverbindung erstellen
engine = create_engine('sqlite:///workspace/smartphone_dealer_data.db')

# SQL Abfrage
df_sub = pd.read_sql_query("""SELECT *
                              FROM phones;""",
                          con=engine)

# Schliessen der Datenbankverbindung
engine.dispose()

df_sub 
```
</div>

## <b>Aufgaben (Hinweis: Dieser Teil wird bewertet)</b>
<b style="color:blue;">Hinweise zu den folgenden Aufgaben:</b>
<ul style="color:blue;">
  <li>Erstellen Sie je Aufgabe eine SQL Abfrage und integrieren Sie diese in Ihren Python Code.</li>
  <li>Speichern Sie je Aufgabe die Ergebnistabelle in einem DataFrame und stellen Sie diesen ganz oder in Teilen (z.B. erste 5 Zeilen) dar.</li>
</ul>

#### <b>Aufgabe (1): Listen Sie alle Kunden auf, welche mit Vornamen John oder Sophia heissen.</b>
<b>Details zur Aufgabenstellung:</b>
- Sie finden die benötigte Informationen in der Tabelle 'Customers'.

<b style="color: gray;">(max. erreichbare Punkte: 4)</b>

In [6]:
# Engine für Datenbankverbindung erstellen
engine = create_engine(db_connection_url)

# Abfrage erstellen und Ergebnis in einem DataFrame speichern

with engine.connect() as connection:
    result = connection.execute(text('''SELECT * FROM customers 
                                    WHERE firstname LIKE 'John' 
                                    OR firstname LIKE 'Sophia' 
                                    Limit 10  
                                    '''))

df_query1 = pd.DataFrame(result.fetchall())

# Datenbankverbindung trennen
engine.dispose()

# Ergebnis anzeigen
### 'print(df_query1)' wäre auch eine Alternative, kommt aber leicht anders daher

df_query1

,customerid,firstname,lastname,phone,email,address
0,CUZ6NEGT1KC6,John,Brown,+41 (0)1748330217,customer4@example.com,"64083 Oak St, City, Country"
1,CU8VPHA9FOMH,Sophia,Jones,+41 (0)9903831451,customer5@example.com,"19092 Oak St, City, Country"
2,CUITIA6FINIX,John,Brown,+41 (0)1847224247,customer7@example.com,"71885 Elm St, City, Country"
3,CUG79HUA45AA,John,Davis,+41 (0)2748924051,customer12@example.com,"04362 Elm St, City, Country"
4,CUEYIGLKMYGK,John,Smith,+41 (0)8500639146,customer13@example.com,"27193 Spruce St, City, Country"
5,CU0ZTP23OM44,John,Smith,+41 (0)7890108240,customer19@example.com,"90202 Pine St, City, Country"
6,CU7Y0JD7LD9O,Sophia,Jones,+41 (0)4395087007,customer23@example.com,"57188 Oak St, City, Country"
7,CU1QPGU3U7LN,Sophia,Martinez,+41 (0)8111974476,customer24@example.com,"82030 Ash St, City, Country"
8,CUR9WI0J9Z19,Sophia,Garcia,+41 (0)1970846958,customer28@example.com,"11513 Maple St, City, Country"
9,CUY701LB7AWY,John,Brown,+41 (0)4600744958,customer29@example.com,"75265 Birch St, City, Country"

Alternativer Codeblock, aus einem anderen Beispiel übernommen. Ab Aufgabenteil 4 verwende ich diesen Approach nur noch

In [8]:
### Alternativer Block to  first query above with shorter actual query block:
# Engine für Datenbankverbindung erstellen
engine = create_engine(db_connection_url)

# Abfrage erstellen und Ergebnis in einem DataFrame speichern

df_sub = pd.read_sql_query('''SELECT * FROM customers 
                                    WHERE firstname LIKE 'John' 
                                    OR firstname LIKE 'Sophia' 
                                    Limit 10 ''', 
                          con=engine)

# Datenbankverbindung trennen
engine.dispose()

# Ergebnis anzeigen
df_sub

,customerid,firstname,lastname,phone,email,address
0,CUZ6NEGT1KC6,John,Brown,+41 (0)1748330217,customer4@example.com,"64083 Oak St, City, Country"
1,CU8VPHA9FOMH,Sophia,Jones,+41 (0)9903831451,customer5@example.com,"19092 Oak St, City, Country"
2,CUITIA6FINIX,John,Brown,+41 (0)1847224247,customer7@example.com,"71885 Elm St, City, Country"
3,CUG79HUA45AA,John,Davis,+41 (0)2748924051,customer12@example.com,"04362 Elm St, City, Country"
4,CUEYIGLKMYGK,John,Smith,+41 (0)8500639146,customer13@example.com,"27193 Spruce St, City, Country"
5,CU0ZTP23OM44,John,Smith,+41 (0)7890108240,customer19@example.com,"90202 Pine St, City, Country"
6,CU7Y0JD7LD9O,Sophia,Jones,+41 (0)4395087007,customer23@example.com,"57188 Oak St, City, Country"
7,CU1QPGU3U7LN,Sophia,Martinez,+41 (0)8111974476,customer24@example.com,"82030 Ash St, City, Country"
8,CUR9WI0J9Z19,Sophia,Garcia,+41 (0)1970846958,customer28@example.com,"11513 Maple St, City, Country"
9,CUY701LB7AWY,John,Brown,+41 (0)4600744958,customer29@example.com,"75265 Birch St, City, Country"

#### <b>Aufgabe (2): Selektieren Sie die Telefone von "Samsung", und geben Sie deren Preise als Ganzzahlen (INTEGER) zurück.</b>
<b>Details zur Aufgabenstellung:</b>
- Sie finden die benötigten Informationen in der Tabelle 'Phones'.
- Die Ergebnistabelle muss die Spalten: 'PhoneID',  'Brand' und den Price als Ganzzahl (INTEGER) enthalten.
- Ordnen Sie die Tabelle absteigend nach Price als Ganzzahl (INTEGER).
- Limitieren Sie die Anzahl der mit der SQL Abfrage zurückgegebenen Phones auf 10.

<b style="color: gray;">(max. erreichbare Punkte: 4)</b>

In [7]:
# Engine für Datenbankverbindung erstellen
engine = create_engine(db_connection_url)

# Abfrage erstellen und Ergebnis in einem DataFrame speichern

with engine.connect() as connection:
    result = connection.execute(text('''SELECT phoneid, brand, cast(price as integer) FROM phones 
                                    WHERE brand LIKE 'Samsung' 
                                    ORDER BY Price DESC LIMIT 10
                                    '''))

df_query2=pd.DataFrame(result.fetchall())

# Datenbankverbindung trennen
engine.dispose()

# Ergebnis anzeigen
### To Do
print(df_query2)

       phoneid    brand  price
0  PRSVWQKWG5S  Samsung   1200
1  PR452SG9VL5  Samsung   1199
2  P4NZ1YLM2TI  Samsung   1199
3  P3KPFEFH1F7  Samsung   1199
4  PC1M86UT012  Samsung   1198
5  P0ANLRVWKQ4  Samsung   1198
6  PLN0SZL6U9G  Samsung   1197
7  PVROBGZ8PAH  Samsung   1196
8  PB0HVE5I7VS  Samsung   1195
9  P70LJGX90PK  Samsung   1193

#### <b>Aufgabe (3): Welches sind alle Telefonmodelle, die zwischen 2021 und 2023 auf den Markt kamen, einen IMEI-Wert haben und mehr als 800 USD kosten?</b>
<b>Details zur Aufgabenstellung:</b>
- Sie finden die benötigten Informationen in der Tabelle 'Phones'.
- Ordnen Sie die Ergebnisse absteigend nach Price.

<b style="color: gray;">(max. erreichbare Punkte: 4)</b>

In [8]:
# Engine für Datenbankverbindung erstellen
engine = create_engine(db_connection_url)

# Abfrage erstellen und Ergebnis in einem DataFrame speichern
with engine.connect() as connection:
    result = connection.execute(text('''SELECT model, year, imei, price FROM phones 
                                        WHERE imei IS NOT NULL 
                                        AND year BETWEEN 2021 AND 2023 
                                        AND price>800 ORDER BY price DESC
                                        '''))
    # select statement purposefully limited to 20 rows for readability

df_query3=pd.DataFrame(result.fetchall())

# Datenbankverbindung trennen
engine.dispose()

# Ergebnis anzeigen
print(df_query3)

        model  year             imei    price
0   iPhone 13  2021  820233546949476  1199.93
1      8.3 5G  2022  186189391481759  1199.91
2       Mi 11  2022  736745637323702  1199.25
3   iPhone 13  2023  268997797693553  1199.25
4    Xperia 5  2023  232603272638587  1199.22
5   iPhone 13  2023   73666573591666  1199.21
6         P40  2022  916454881565370  1199.16
7   OnePlus 9  2022  908917087341639  1199.13
8      8.3 5G  2021  415484784299736  1199.04
9   iPhone 13  2021  592307664358069  1199.00
10    Pixel 6  2021  287989008632471  1198.92
11        P40  2021  945272385665427  1198.91
12   Xperia 5  2022  593591582804294  1198.80
13        P40  2023   45884491620099  1198.62
14      Mi 11  2023  467640560385944  1198.61
15     Reno 6  2022  395470130903635  1198.27
16  OnePlus 9  2023  551934840178315  1198.23
17     8.3 5G  2023  235102071515963  1198.09
18     Reno 6  2021  105766791759902  1197.83
19     8.3 5G  2021  817811625549261  1197.69

#### <b>Aufgabe (4): Ermitteln Sie alle Verkäufe, die von der Verkäuferin "Diana Morris" durchgeführt wurden.</b>
<b>Details zur Aufgabenstellung:</b>
- Geben Sie Verkaufspreis, Datum und die Namen der Kunden aus.
- Sie finden die benötigten Informationen in den Tabellen 'Sales', 'SalesPersons' und 'Customers'.

<b style="color: gray;">(max. erreichbare Punkte: 4)</b>

In [9]:
# Engine für Datenbankverbindung erstellen
engine = create_engine(db_connection_url)

# Abfrage erstellen und Ergebnis in einem DataFrame speichern
### ab hier habe ich einen kürzeren Ansatz gewählt 
df_query4=pd.read_sql_query(''' SELECT  a.saledate, a.saleprice, c.firstname, c.lastname
                                FROM sales a 
                                JOIN salespersons b on a.salespersonid = b.salespersonid
                                JOIN customers c on a.customerid = c.customerid
                                WHERE b.firstname='Diana' AND b.lastname='Morris'
                            ''', con=engine)

# Datenbankverbindung trennen
engine.dispose()

# Ergebnis anzeigen
### Teil von neuen Ansatz
df_query4

       saledate  saleprice firstname   lastname
0    2021-01-31     550.98   Jessica      Davis
1    2023-09-30     505.83     Sarah   Williams
2    2022-05-31     966.40    Sophia  Rodriguez
3    2022-08-31     809.61     Chris      Davis
4    2021-09-30     924.66   Michael  Rodriguez
..          ...        ...       ...        ...
342  2021-12-31     871.37    Robert   Williams
343  2021-11-30     683.36     David     Miller
344  2022-01-31     482.95     Chris      Davis
345  2023-06-30     626.23     David      Davis
346  2023-11-30     440.97     Chris   Martinez

[347 rows x 4 columns]

#### <b>Aufgabe (5): Ermitteln Sie die Namen der Kunden und die Modelle der Telefone, welche diese gekauft haben, aber nur die Verkäufe über 600 USD.</b>
<b>Details zur Aufgabenstellung:</b>
- Sie finden die benötigten Informationen in den Tabellen 'Sales', 'Customers' und 'Phones'.
- Ordnen Sie die Tabelle absteigend nach SaleDate.

<b style="color: gray;">(max. erreichbare Punkte: 4)</b>

In [10]:
# Engine für Datenbankverbindung erstellen
engine = create_engine(db_connection_url)

# Abfrage erstellen und Ergebnis in einem DataFrame speichern
df_query5=pd.read_sql_query(''' SELECT c.model, b.firstname, b.lastname, a.saleprice FROM sales a
                                JOIN Customers b ON a.customerid = b.customerid
                                JOIN phones c ON a.phoneid = c.phoneid
                                WHERE a.saleprice > 600
                                ORDER BY a.saledate DESC
                            ''', con=engine)

# Datenbankverbindung trennen
engine.dispose()

# Ergebnis anzeigen
df_query5

           model firstname  lastname  saleprice
0            P40     Chris     Brown     709.52
1      OnePlus 9     Emily  Martinez     857.68
2      OnePlus 9   Michael     Davis     739.14
3      V60 ThinQ     Emily  Martinez     910.01
4      OnePlus 9     Emily     Davis     816.64
...          ...       ...       ...        ...
1241   iPhone 13   Jessica   Johnson     614.06
1242         P40    Robert  Martinez     902.95
1243      Reno 6    Ashley  Williams     891.48
1244  Galaxy S21      John    Garcia     698.16
1245   OnePlus 9   Jessica  Williams     991.73

[1246 rows x 4 columns]

#### <b>Aufgabe (6): Ermitteln Sie den durchschnittlichen Verkaufspreis und die Anzahl der Verkäufe für jeden Verkäufer, aber nur für Verkäufer, die mehr als 10 Verkäufe getätigt haben.</b>
<b>Details zur Aufgabenstellung:</b>
- Sie finden die benötigten Informationen in den Tabellen 'SalesPersons' und 'Sales'.
- Ordnen Sie die Tabelle absteigend nach der Anzahl der Verkäufe.

<b style="color: gray;">(max. erreichbare Punkte: 8)</b>

In [11]:
# Engine für Datenbankverbindung erstellen
engine = create_engine(db_connection_url)

# Abfrage erstellen und Ergebnis in einem DataFrame speichern
df_query6=pd.read_sql_query(''' SELECT avg(a.saleprice), count(a.saleid),  b.firstname, b.lastname
                                FROM sales a
                                JOIN salespersons b ON a.salespersonid = b.salespersonid 
                                GROUP BY a.salespersonid, b.firstname, b.lastname
                                HAVING count(saleid) > 10
                            ''', con=engine)
### is this a trap question? I can only find 5 seller and all of them have way more than 10 sales

# Datenbankverbindung trennen
engine.dispose()

# Ergebnis anzeigen
df_query6

          avg  count firstname lastname
0  697.247465    359       Bob      Kim
1  700.886772    347     Diana   Morris
2  706.055054    368    Edward    Evans
3  697.212539    382   Charlie    Patel
4  692.154354    379     Alice   Nguyen

#### <b>Aufgabe (7): Ermitteln Sie die Anzahl der Reparaturen, die von jedem Techniker durchgeführt wurden.</b>
<b>Details zur Aufgabenstellung:</b>
- Sie finden die benötigten Informationen in den Tabellen 'Technicians' und 'ServiceRecords'.
- Geben Sie den Vornamen und Nachnamen des Technikers sowie die Anzahl der Reparaturen an.
- Ordnen Sie die Ergebnistabelle absteigend nach Anzahl der Reparaturen.

<b style="color: gray;">(max. erreichbare Punkte: 8)</b>

In [12]:
# Engine für Datenbankverbindung erstellen
engine = create_engine(db_connection_url)

# Abfrage erstellen und Ergebnis in einem DataFrame speichern
df_query7=pd.read_sql_query(''' SELECT Count(a.serviceid), b.firstname, b.lastname FROM servicerecords a 
                            JOIN technicians b ON a.technicianid = b.technicianid
                            GROUP by b.technicianid, b.firstname, b.lastname
                            ORDER BY count(a.serviceid) DESC
                            ''', con=engine)


# Datenbankverbindung trennen
engine.dispose()

# Ergebnis anzeigen
df_query7

    count firstname lastname
0      72      Kyle   Santos
1      65      Ivan      Lee
2      63    Olivia   Santos
3      60    Olivia   Santos
4      57    Sophia   Watson
5      46       Mia   Santos
6      46      Ivan   Watson
7      46      Kyle   Santos
8      46      Liam  Roberts
9      46      Greg  Roberts
10     46    Sophia    Clark
11     46    Sophia   Turner
12     45      Greg   Turner
13     45      Liam   Santos
14     44       Mia      Lee

#### <b>Aufgabe (8): Ermitteln Sie die Anzahl der Verkäufe pro Verkäufer und den durchschnittlichen Verkaufspreis pro Verkäufer.</b>
<b>Details zur Aufgabenstellung: </b>
- Sie finden die benötigten Informationen in den Tabellen 'SalesPersons' und 'Sales'.
- Verwenden Sie nur Verkäufe, deren Verkaufspreis über 500 USD liegt.
- Runden Sie den durchschnittlichen Verkaufspreis auf zwei Nachkommastellen.
- Sortieren Sie die Ergebnisse nach der Anzahl der Verkäufe und zeigen Sie nur die Top 5 Verkäufer an.

<b style="color: gray;">(max. erreichbare Punkte: 8)</b>

In [13]:
# Engine für Datenbankverbindung erstellen
engine = create_engine(db_connection_url)

# Abfrage erstellen und Ergebnis in einem DataFrame speichern
df_query8=pd.read_sql_query('''SELECT count(a.saleid), round(cast(avg(a.saleprice) as NUMERIC),2) , b.firstname, b.lastname
                            FROM sales a
                            JOIN salespersons b ON a.salespersonid = b.salespersonid
                            WHERE a.saleprice > 500
                            GROUP BY b.salespersonid, b.firstname, b.lastname
                            ORDER BY count(a.saleid)
                            LIMIT 5 
                            ''', con=engine)


# Datenbankverbindung trennen
engine.dispose()

# Ergebnis anzeigen
df_query8

   count   round firstname lastname
0    291  749.49     Diana   Morris
1    299  746.88       Bob      Kim
2    311  744.91     Alice   Nguyen
3    314  750.71    Edward    Evans
4    320  745.52   Charlie    Patel

### Jupyter notebook --footer info-- (please always provide this at the end of each notebook)

In [ ]:
import os
import platform
import socket
from platform import python_version
from datetime import datetime

print('-----------------------------------')
print(os.name.upper())
print(platform.system(), '|', platform.release())
print('Datetime:', datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
print('Python Version:', python_version())
print('IP Address:', socket.gethostbyname(socket.gethostname()))
print('-----------------------------------')